[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
loglevel=info

[program:api]
command=flask run --host=0.0.0.0 --port=5003
directory=/app
environment=FLASK_APP="api.app",PYTHONUNBUFFERED="1"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scraper]
command=python -m scraper.main
directory=/app
environment=PYTHONUNBUFFERED="1"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
